import {
  mdiAlertCircle,
  mdiArrowDown,
  mdiArrowUp,
  mdiBattery,
  mdiBatteryAlert,
  mdiBatteryCharging,
  mdiBell,
  mdiBellOutline,
  mdiCheckCircle,
  mdiChevronDown,
  mdiChevronUp,
  mdiClockOutline,
  mdiCloudCheck,
  mdiCog,
  mdiCpu64Bit,
  mdiCubeOutline,
  mdiDatabase,
  mdiDocker,
  mdiDownload,
  mdiEthernet,
  mdiExpansionCard,
  mdiFan,
  mdiFlash,
  mdiFolder,
  mdiHarddisk,
  mdiHarddiskPlus,
  mdiInformation,
  mdiLanConnect,
  mdiMemory,
  mdiMonitor,
  mdiPause,
  mdiPlay,
  mdiPower,
  mdiRestart,
  mdiServer,
  mdiServerNetwork,
  mdiShieldAlert,
  mdiShieldCheck,
  mdiSpeedometer,
  mdiStop,
  mdiUpload,
  mdiUsbFlashDrive,
  mdiViewGrid,
  mdiViewList,
  mdiWrench,
} from "@mdi/js";
import { html, type TemplateResult } from "lit";

export {
  mdiAlertCircle,
  mdiArrowDown,
  mdiArrowUp,
  mdiBattery,
  mdiBatteryAlert,
  mdiBatteryCharging,
  mdiBell,
  mdiBellOutline,
  mdiCheckCircle,
  mdiChevronDown,
  mdiChevronUp,
  mdiClockOutline,
  mdiCloudCheck,
  mdiCog,
  mdiCpu64Bit,
  mdiCubeOutline,
  mdiDatabase,
  mdiDocker,
  mdiDownload,
  mdiEthernet,
  mdiExpansionCard,
  mdiFan,
  mdiFlash,
  mdiFolder,
  mdiHarddisk,
  mdiHarddiskPlus,
  mdiInformation,
  mdiLanConnect,
  mdiMemory,
  mdiMonitor,
  mdiPause,
  mdiPlay,
  mdiPower,
  mdiRestart,
  mdiServer,
  mdiServerNetwork,
  mdiShieldAlert,
  mdiShieldCheck,
  mdiSpeedometer,
  mdiStop,
  mdiUpload,
  mdiUsbFlashDrive,
  mdiViewGrid,
  mdiViewList,
  mdiWrench,
};

export function iconTemplate(
  path: string,
  size = 20,
  className = "icon"
): TemplateResult {
  return html`
    <svg
      class="${className}"
      style="width: ${size}px; height: ${size}px;"
      viewBox="0 0 24 24"
    >
      <path d="${path}" fill="currentColor"></path>
    </svg>
  `;
}
